//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class process {
    
    private string inputbufField;
    
    private processExecutionStackFrame[][] executionStackField;
    
    private string idField;
    
    private string taskpriorityField;
    
    private string logusedField;
    
    private string waitresourceField;
    
    private string waittimeField;
    
    private string ownerIdField;
    
    private string transactionnameField;
    
    private string lasttranstartedField;
    
    private string xDESField;
    
    private string lockModeField;
    
    private string scheduleridField;
    
    private string kpidField;
    
    private string statusField;
    
    private string spidField;
    
    private string sbidField;
    
    private string ecidField;
    
    private string priorityField;
    
    private string trancountField;
    
    private string lastbatchstartedField;
    
    private string lastbatchcompletedField;
    
    private string lastattentionField;
    
    private string clientappField;
    
    private string hostnameField;
    
    private string hostpidField;
    
    private string loginnameField;
    
    private string isolationlevelField;
    
    private string xactidField;
    
    private string currentdbField;
    
    private string lockTimeoutField;
    
    private string clientoption1Field;
    
    private string clientoption2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string inputbuf {
        get {
            return this.inputbufField;
        }
        set {
            this.inputbufField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("frame", typeof(processExecutionStackFrame), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public processExecutionStackFrame[][] executionStack {
        get {
            return this.executionStackField;
        }
        set {
            this.executionStackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taskpriority {
        get {
            return this.taskpriorityField;
        }
        set {
            this.taskpriorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string logused {
        get {
            return this.logusedField;
        }
        set {
            this.logusedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string waitresource {
        get {
            return this.waitresourceField;
        }
        set {
            this.waitresourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string waittime {
        get {
            return this.waittimeField;
        }
        set {
            this.waittimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ownerId {
        get {
            return this.ownerIdField;
        }
        set {
            this.ownerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transactionname {
        get {
            return this.transactionnameField;
        }
        set {
            this.transactionnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lasttranstarted {
        get {
            return this.lasttranstartedField;
        }
        set {
            this.lasttranstartedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string XDES {
        get {
            return this.xDESField;
        }
        set {
            this.xDESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lockMode {
        get {
            return this.lockModeField;
        }
        set {
            this.lockModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string schedulerid {
        get {
            return this.scheduleridField;
        }
        set {
            this.scheduleridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kpid {
        get {
            return this.kpidField;
        }
        set {
            this.kpidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string spid {
        get {
            return this.spidField;
        }
        set {
            this.spidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sbid {
        get {
            return this.sbidField;
        }
        set {
            this.sbidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ecid {
        get {
            return this.ecidField;
        }
        set {
            this.ecidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trancount {
        get {
            return this.trancountField;
        }
        set {
            this.trancountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lastbatchstarted {
        get {
            return this.lastbatchstartedField;
        }
        set {
            this.lastbatchstartedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lastbatchcompleted {
        get {
            return this.lastbatchcompletedField;
        }
        set {
            this.lastbatchcompletedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lastattention {
        get {
            return this.lastattentionField;
        }
        set {
            this.lastattentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clientapp {
        get {
            return this.clientappField;
        }
        set {
            this.clientappField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hostname {
        get {
            return this.hostnameField;
        }
        set {
            this.hostnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hostpid {
        get {
            return this.hostpidField;
        }
        set {
            this.hostpidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string loginname {
        get {
            return this.loginnameField;
        }
        set {
            this.loginnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isolationlevel {
        get {
            return this.isolationlevelField;
        }
        set {
            this.isolationlevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xactid {
        get {
            return this.xactidField;
        }
        set {
            this.xactidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currentdb {
        get {
            return this.currentdbField;
        }
        set {
            this.currentdbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lockTimeout {
        get {
            return this.lockTimeoutField;
        }
        set {
            this.lockTimeoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clientoption1 {
        get {
            return this.clientoption1Field;
        }
        set {
            this.clientoption1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clientoption2 {
        get {
            return this.clientoption2Field;
        }
        set {
            this.clientoption2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class processExecutionStackFrame {
    
    private string lineField;
    
    private string stmtstartField;
    
    private string stmtendField;
    
    private string sqlhandleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stmtstart {
        get {
            return this.stmtstartField;
        }
        set {
            this.stmtstartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stmtend {
        get {
            return this.stmtendField;
        }
        set {
            this.stmtendField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sqlhandle {
        get {
            return this.sqlhandleField;
        }
        set {
            this.sqlhandleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("blocked-process-report", Namespace="", IsNullable=false)]
public partial class blockedprocessreport {
    
    private process[][] blockedprocessField;
    
    private process[][] blockingprocessField;
    
    private string monitorLoopField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("blocked-process", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("process", typeof(process), IsNullable=false)]
    public process[][] blockedprocess {
        get {
            return this.blockedprocessField;
        }
        set {
            this.blockedprocessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("blocking-process", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("process", typeof(process), IsNullable=false)]
    public process[][] blockingprocess {
        get {
            return this.blockingprocessField;
        }
        set {
            this.blockingprocessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string monitorLoop {
        get {
            return this.monitorLoopField;
        }
        set {
            this.monitorLoopField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class BlockedProcesses {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("blocked-process-report", typeof(blockedprocessreport))]
    [System.Xml.Serialization.XmlElementAttribute("process", typeof(process))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
